modLoader = "javafml"
loaderVersion = "[39,)"
license = "All rights reserved"
[[mods]]
logoFile = "icon.png"
modId = "clockwork_creations"
version = "${file.jarVersion}"
displayName = "Clockwork Creations"
authors = "Sammy;"
description = '''
A small mod centered around clocks.
'''
[[dependencies.clockwork_creations]]
modId = "forge"
mandatory = true
versionRange = "[40.2,)"
ordering = "NONE"
side = "BOTH"